name: Create or Update Issue from Obsidian Notes

on:
  push:
    paths:
      - "notes_to_github/*.md"

jobs:
  create_issue:
    runs-on: ubuntu-latest
    env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Notes and Create Issues
        run: |
          git diff --name-only HEAD^ HEAD | grep 'notes_to_github/.*\.md' | while read FILE; do
            TITLE=$(grep -i -m 1 '^title:' "$FILE" | cut -d':' -f2- | xargs)
            LABELS=$(awk '/^tags:/ {p=1; next} p && /^  -/ {print substr($0,3)} !/^  -/ {p=0}' "$FILE" | tr '\n' ',')
            CONTENT=$(awk '/^## /{p=1} p' "$FILE")
            EXISTING_ISSUE=$(gh issue list --search "$TITLE" --state open --json title,number | jq -r --arg TITLE "$TITLE" '.[] | select(.title == $TITLE) | .number')

            if [ -z "$EXISTING_ISSUE" ]; then
              echo "Creating a new issue for $FILE"
              gh issue create \
                --title "$TITLE" \
                --body "$CONTENT" \
                --label "$LABELS" \
                --assignee "genga6"
            else
              echo "Updating existing issue #$EXISTING_ISSUE"
              gh issue edit $EXISTING_ISSUE --body "$CONTENT"
            fi
          done