name: Create or Update Pull Request from Obsidian Notes

on:
  push:
    paths:
      - "notes_to_github/*.md"

jobs:
  create_or_update_pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Notes and Create PR
        run: |
          for FILE in $(git diff --name-only origin/main | grep 'notes_to_github/.*\.md'); do
            TITLE=$(basename "$FILE" .md)
            CONTENT=$(awk '/^## /{p=1} p' "$FILE")
            LABELS=$(awk '/^#/{print $0}' "$FILE" | tr '\n' ',' | sed 's/,*$//')

            echo "Processing $FILE"

            EXISTING_PR=$(gh pr list --state open --base main --json title,number | jq -r --arg TITLE "Update: $TITLE" '.[] | select(.title == $TITLE) | .number')

            if [ -z "$EXISTING_PR" ]; then
              echo "Creating a new PR for $FILE"
              gh pr create \
                --title "Update: $TITLE" \
                --body "$CONTENT" \
                --base main \
                --label "$LABELS"
            else
              echo "Updating existing PR #$EXISTING_PR"
              gh pr edit "$EXISTING_PR" --body "$CONTENT"
            fi
          done