name: Create or Update Issues from Obsidian Notes

on:
  push:
    paths:
      - "notes_to_github/*.md"

jobs:
  create_or_update_issues:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Fetch main branch
        run: |
          git fetch origin main     

      - name: Extract Notes and Create Issues
        run: |
          git diff --name-only HEAD^ | grep 'notes_to_github/.*\.md' | while IFS= read -r FILE; do
            TITLE=$(basename "$FILE" .md)
            CONTENT=$(cat "$FILE")
            LABELS=$(awk '/^## Labels/{p=1; next} /^## /{p=0} p {for (i=1; i<=NF; i++) if ($i ~ /^#[A-Za-z0-9_-]+$/) print substr($i,2)}' "$FILE")
            echo "Processing $FILE"

            EXISTING_ISSUE=$(gh issue list --state open --json number,title | jq -r ".[] | select(.title == \"$TITLE\") | .number")

            if [ -z "$EXISTING_ISSUE" ]; then
              echo "Creating a new issue for $FILE"
              gh issue create \
                --title "$TITLE" \
                --body "$CONTENT" \
                $(echo "$LABELS" | tr ' ' '\n' | awk '{print "--label " $1}')
            else
              echo "Updating existing issue #$EXISTING_ISSUE"
              gh issue edit "$EXISTING_ISSUE" --body "$CONTENT"

              EXISTING_LABELS=$(gh issue view "$EXISTING_ISSUE" --json labels -q '.labels[].name')
              echo "$EXISTING_LABELS" | while IFS= read -r label; do
                gh issue edit "$EXISTING_ISSUE" --remove-label "$label"
              done
              
              if [ -n "$EXISTING_LABELS" ]; then
                echo "$LABELS" | while IFS= read -r label; do
                  gh issue edit "$EXISTING_ISSUE" --add-label "$label"
                done
              fi

              if [ -n "$LABELS" ]; then
                gh issue edit "$EXISTING_ISSUE" $(echo "$LABELS" | tr ' ' '\n' | awk '{print "--add-label " $1}')
              fi
            fi
          done