name: Create Issue from Obsidian Notes

on:
  push:
    paths:
      - "notes_to_github/*.md"

jobs:
  create_issue:
    runs-on: ubuntu-latest
    env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Notes and Create Issues
        run: |
          git diff --name-only HEAD^ HEAD | grep 'notes_to_github/.*\.md' | while read FILE; do
            TITLE=$(head -n 1 "$FILE")

            RAW_LABELS=$(grep '^#labels:' "$FILE" | cut -d':' -f2- | xargs)
            LABELS=$(echo "$RAW_LABELS" | sed 's/, */,/g') 

            CONTENT=$(awk '!/^#labels:/{print}' "$FILE" | tail -n +2)

            EXISTING_ISSUE=$(gh issue list --search "$TITLE" --state open --json number --jq '.[0].number')

            if [ -z "$EXISTING_ISSUE" ]; then
              echo "Creating a new issue for $FILE"
              gh issue create \
                --title "$TITLE" \
                --body "$CONTENT" \
                --label "$LABELS" \
                --assignee "genga6"
            else
              echo "Updating existing issue #$EXISTING_ISSUE"
              gh issue edit $EXISTING_ISSUE --body "$CONTENT"
            fi
          done