name: Create Issue from Obsidian Notes

on:
  push:
    paths:
      - "notes_to_github/*.md"

jobs:
  create_issue:
    runs-on: ubuntu-latest
    env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Notes and Create Issues
        run: |
          git diff --name-only HEAD^ HEAD | grep 'notes_to_github/.*\.md' | while read FILE; do
            TITLE=$(head -n 1 "$FILE")
            LABELS=$(grep '^#labels:' "$FILE" | cut -d':' -f2 | tr ',' '\n' | xargs | tr ' ' ',')
            CONTENT=$(awk '!/^#labels:/{print}' "$FILE" | tail -n +2)  # #labels: を本文から除外

            echo "Creating issue for $FILE"
            gh issue create \
              --title "$TITLE" \
              --body "$CONTENT" \
              --label "$LABELS" \
              --assignee "genga6"
          done
